### ISSUE TITLE
isImg() aways returns true

### ISSUE THREAD

**Issue by viktorstrate** [d4v1dm013/img-type#2]
The functions `isImg()` does always return true

I think the bug is here on line 278, where it should return false instead?
https://github.com/d4v1dm013/img-type/blob/master/index.js#L277-L279

Maybe some unit tests would be a good idea :)

**Comment by d4v1dm013** [comment]
Hi,

Thanks for your return.

Yes, the error was on line 278, I have fix and commit on version 0.1.14

I will follow your advice for unit testing.

Thank you for your help :)
